### ISSUE TITLE
Add support for more architectures (incl. arm64) in the AUR package

### ISSUE THREAD

**Issue by AlwaysLivid** [cmuench/pacman-auto-update#1]
Since this is simply just a systemd service, it would be very helpful for me if you could change [line 11](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pacman-auto-update#n11) in order to add more architectures; `arch=('i686' 'x86_64')`

Doing so would help me (as well as likely other people) install `pacman-auto-update` more easily on Raspberry Pi 4 systems which I'd like to keep mostly unmaintained-- without any `PKGINFO` modifications that can become obsolete at some point down the line. Thanks!

**Comment by cmuench** [comment]
@AlwaysLivid I madded a list of architectures. Releases as 1.0.0-2.

**Comment by AlwaysLivid** [comment]
Thanks! @cmuench

**Comment by neoxic** [comment]
Could have been more flexible to just permit any architechture:
```
arch=('any')
```
