### ISSUE TITLE
Depends on pacman-contrib

### ISSUE THREAD

**Issue by Wurstnase** [cmuench/pacman-auto-update#15]
Hi,

I don't know how to make a pull request to AUR.
However, the script is calling ```paccache``` which is only installed via pacman-contrib.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pacman-auto-update#n12

https://github.com/cmuench/pacman-auto-update/blob/master/root/usr/lib/pacman-auto-update/pacman-auto-update#L104-L105

Greetings
Nico

**Comment by cmuench** [comment]
@Wurstnase You mean that we add `pacman-contrib` as dependency?

**Comment by cmuench** [comment]
@Wurstnase I released v1.4.1 with the added dependency.

**Comment by Wurstnase** [comment]
Thx, for your fast response :)
I made a new patch.
