### ISSUE TITLE
Quality & Compatiblity for the whole update process.

### ISSUE THREAD

**Issue by Tids** [cmuench/pacman-auto-update#2]
There are many things you really should consider, because right now the auto-update will break a system for sure.

1. Quality
* You should not check every hour, because most mirrors sync in a range of 1-6h. So you do a lot of pressure on them without much need
* It should not try to check when there is no network access
* You might run out of space, because the pkg-cache has grown to big
* With a slow mirror while the user tries to shut down, the user might need to wait a very long time until the download and installation is done. The user might even just turn off the system, because a lack of time, endurance or battery power.

2. Compatiblity
* In many cases, like kernel updates, right after the update you maybe unable to use many things until you have had restarted your computer. Like when it needs to load a kernel module (USB access) or within a new Qt version, that needs a least a login until Qt will find its plugins. So in the middle of work, it's a bad idea to run updates like this.

I'm trying to catch as many as possible with my updater, because I started at the same position as you :). Maybe this will help you in some parts, if needed. https://gitlab.com/Fabish/puu

**Comment by cmuench** [comment]
@Tids Thanks for the hints. I use this package only to update my headless Intel NUC server (with very less installed packages) and not on my workstation. For me it works good enough without any problem.
But I will have your tip in my mind.

I will close this issue, because there is currently no todo for me.
