### ISSUE TITLE
404 - Page Not Found

### ISSUE THREAD

**Issue by voxie12** [cmuench/pacman-auto-update#27]
![image](https://user-images.githubusercontent.com/65469239/230777862-006437af-60cc-4c81-ac6e-b99c62bc085a.png)
i clicked your link and i saw this.

**Comment by cmuench** [comment]
@voxie12 Package was removed from the AUR. They don't want a auto update package.

**Comment by voxie12** [comment]
> @voxie12 Package was removed from the AUR. They don't want a auto update package.

ok, do u know how to install it?

**Comment by cmuench** [comment]
Just clone it on your machine and run `makepkg -i`

**Comment by es20490446e** [comment]
I have just provided **alternative installation methods** in the [readme](https://github.com/cmuench/pacman-auto-update/blob/master/README.md).

**Comment by es20490446e** [comment]
What I'm going to do is make auto-update to build and update its own package.

**Comment by es20490446e** [comment]
Now autoupdate updates its own package.

For that working you shall reinstall it.
