### ISSUE TITLE
Complete history has been overwritten

### ISSUE THREAD

**Issue by Wurstnase** [cmuench/pacman-auto-update#28]
Hi,

please check the history of the master branch. It has been overwritten. The master/main branch should be protected. 

Please reset the branch to the old history.

**Comment by cmuench** [comment]
@Wurstnase I recovered the master branch.

**Comment by Wurstnase** [comment]
Looks still not good? Are you sure that you've recovered the right repo?

**Comment by cmuench** [comment]
@Wurstnase this change was made by @es20490446e 
I just asked him about the commit.

**Comment by Wurstnase** [comment]
My old clone has over 54 commits on the master branch. You may check wurstnase/pacman-auto-update.

**Comment by cmuench** [comment]
@Wurstnase thanks. Data should be back.

**Comment by cmuench** [comment]
master branch is now proteced.

**Comment by Wurstnase** [comment]
Thanks. Hopefully we will find the missing commits after my last pull.

**Comment by es20490446e** [comment]
Sorry, I deleted the history by accident while trying to amend the last commit message.

I will now include the missing pieces... give me a sec.

**Comment by es20490446e** [comment]
Fixed 👍
