### ISSUE TITLE
 sudo: so: Befehl nicht gefunden

### ISSUE THREAD

**Issue by RJGhugo** [cmuench/pacman-auto-update#29]
systemctl status pacman-auto-update

× pacman-auto-update.service - Pacman Auto Update
     Loaded: loaded (/usr/lib/systemd/system/pacman-auto-update.service; enable>
     Active: failed (Result: exit-code) since Thu 2023-05-25 11:26:01 CEST; 7mi>
   Duration: 3.135s
TriggeredBy: ● pacman-auto-update.timer
    Process: 527 ExecStart=/usr/bin/pacman-auto-update (code=exited, status=1/F>
   Main PID: 527 (code=exited, status=1/FAILURE)
        CPU: 755ms

Mai 25 11:25:58 xxx-workstation systemd[1]: Started Pacman Auto Update.
Mai 25 11:26:01 xxx-workstation pacman-auto-update[1001]: sudo: so: Befehl nich>
Mai 25 11:26:01 xxx-workstation systemd[1]: pacman-auto-update.service: Main pr>
Mai 25 11:26:01 xxx-workstation systemd[1]: pacman-auto-update.service: Failed

**Comment by cmuench** [comment]
@RJGhugo the package was removed from AUR.
Did you use the manual installation way described in the README?

**Comment by cmuench** [comment]
@RJGhugo I can reproduce the issue.

@es20490446e It seems that `sudo` cannot see the `so` bash function. Do you know a way to handle that?

**Comment by es20490446e** [comment]
Yes, it's just a matter of puttin so before sudo.

I will fix it in a moment.

**Comment by es20490446e** [comment]
Fixed: Try now.

**Comment by RJGhugo** [comment]
Thanks very much for fixing it!

**Comment by es20490446e** [comment]
And thanks for letting us know 👍
